### ISSUE TITLE
Feedback provided to me by a colleague

### ISSUE THREAD

**Issue by gkholman** [srowlison/bbiller#2]
Below are comments I've received from a colleague as input to revising the public materials, posted provided they are unattributed.  My edits remove off-topic discussion in the email.

. . . . . . Ken

As an aside, the "official" white paper  
(https://bbiller.com/wp-content/uploads/2017/04/Whitepaper-Blockchain-Biller.pdf) would benefit from a decent amount of editing to make it look less dodgy. And it's a little odd to reference https://lists.oasis-open.org/archives/ubl-dev/201207/msg00000.html. I also note 4d, ie "Structured documents complying with international standards (OASIS UBL), could be accepted in the  
future".
...
Using the blockchain to disrupt the supply chain process is being  
worked on by a number of people at present.

I'm assuming you have some familiarity with stuff like:
https://www.hyperledger.org/
https://hbr.org/2017/03/global-supply-chains-are-about-to-get-better-thanks-to-blockchain
http://www.supplychain247.com/article/transforming_your_business_networks_with_blockchain
http://www.supplychain247.com/article/worlds_largest_mining_company_to_use_blockchain_for_supply_chain/ethereum_foundation

Then there's similar-area-but-different-purpose stuff like  
https://azure.microsoft.com/en-us/blog/can-blockchain-secure-supply-chains-improve-operations-and-solve-humanitarian-issues/, similar to initiatives like  
http://www.foodblockchain.xyz/
https://www.provenance.org (referenced in the above HBR piece).

And stuff like https://blockcat.io (effectively templates for smart  
contracts). (Not to mention the 1001 other ICOs floating about.)
...
Not to suggest naivete on your part, as you've been around a lot  
longer than I, but while the concept is intriguing (ie UBL on the  
blockchain), the implementation (ie bBiller) raises a few concerns.

If I'm reading the whitepaper and  
https://github.com/srowlison/bbiller/issues/1 correctly it would  
appear that majority control will rest in the founder. (Aside: that  
two of the three named individuals associated with the product are  
having a conversation in the comments due to a lack of clarity is not  
confidence-inducing.)

There's growing concern over the use of ICOs to raise funds due to the  
perception that people are capitalising on "hot" tech to make a few  
quick bucks.

I signed up to view the bBiller wiki, and there is nothing there.

https://www.google.co.nz/url?sa=t&rct=j&q=&esrc=s&source=web&cd=8&cad=rja&uact=8&ved=0ahUKEwiwytzLjsfUAhUBn5QKHUqUDVMQFghkMAc&url=http%3A%2F%2Fwww.aph.gov.au%2FDocumentStore.ashx%3Fid%3Df0a62ced-02b7-48e4-88e8-208197c787c8%26subId%3D302079&usg=AFQjCNF0GodSAlIv96E7sw2458AXtp-Jpw
http://www.coindesk.com/diamond-circle-suspends-operations-amid-cash-crisis/
https://www.reddit.com/r/BitcoinAUS/comments/42oy2m/global_media_and_equity_ltd_lists_on_counterparty/
https://www.reddit.com/r/BitcoinAUS/comments/3znm0d/buy_bitcoin_with_amex_visa_and_mastercard_aud/
https://www.reddit.com/r/BitcoinAUS/comments/4c77ut/smsbitcoin_closes/

**Comment by srowlison** [comment]
1. Whitepaper.  4d . The focus is to balance the smart contract innovation and the UBL schema, but also support other interfaces such as OCR, if required.  Work has also commenced on the Design tool which generates the XML and the SOL. Several projects are already underway at client expense..

2. If you check the issue statement on Issue #1, I the Founder only has one vote.  Unfortunately there is no perfect means yet to confirm that any member voted on an issue only once.  If it was found that a member voted more than once on an issue, then that would cause the DAO a problem.  The best we can do is register identities and follow the transactions made.  Bad actors are usually found out eventually.

4. I have updated the Wiki and put the words, "Nothing here yet". 

Thanks for your comments.  My list of successes eclipses the failures.  I also note that Ken values your views and I appreciate your critique and concerns.
